### ISSUE TITLE
ne kadar saglikli?

### ISSUE THREAD

**Issue by set** [ademalidurmus/fatura#1]
Selam, bir projemde efatura entegrasyonu yapmak istiyorum, bu yontem ile gelistirilmis bir efatura entegrasyonu sizce ne kadar saglikli? Anladigim kadariyla earsive official bir yolla erisilmiyor, bunun ozellikle resmi tarafta bir sikinti cikarma ihtimali nedir?

Tesekkurler.

**Comment by ademalidurmus** [comment]
Merhaba,

Bildigim kadari ile GIB'in disariya acik e-Arsiv API dokumantasyonu mevcut degil. Bu yontem ile bir uygulama gelistirildiginde, GIB tarafindan yapilan gelistirmelerin takip edilmesi ve kutuphanenin surekli guncel tutulmasi gerekiyor. GIB sadece kendi arayuzunu kullanarak islem yapmayi zorunlu tutmak isteseydi servise bu sekilde bir kisitlama zaten getirirdi, suan bu sekilde bir kisitlama gorunmuyor.

`Resmi tarafta bir sikinti cakmasi`ndan kastiniz, `Resmi bir kurumun kullanacagi urunu gelistirilirken bu yontem ile GIB servisinden islem yaparsam ne olur?` seklinde ise resmi yazisma ile erisim saglayacaginiz servis hakkinda GIB'den bilgi talep etmenizi oneririm. Aksi taktirde bu yontem ile servise erisim ve kullanimin bir sorun teskil edecegini dusunmuyorum.

Ek olarak servisi bu yontem ile kullanirken, surekli login olunup token temin edilmesi gerektigi icin yuksek adetli kullanimlarda performans sorunlari meydana gelebilir.

**Comment by set** [comment]
Detaylı cevabınız için çok teşekkür ederim :)

**Comment by ademalidurmus** [comment]
Rica eder kolayliklar dilerim.
