### ISSUE TITLE
Sms Doğrulama ve E-imza

### ISSUE THREAD

**Issue by crazyshark2** [ademalidurmus/fatura#3]
Elinize emeğinize sağlık. Ben bir yazılım için geliştirme yapıyorum ve yaptırıyorum fakat sms doğrulaması ve e-imza ile imzalatma yı karşı tarafa anlatamadım. Test sayfasında da sms doğrulama kapatılmış deneyerek ne istediğinide göremiyoruz. Yardımcı olabilirmisiniz. Teşekkür ederim.

**Comment by ademalidurmus** [comment]
Merhaba,
Geri bildiriminiz icin tesekkur ederim. Maalesef sahis veya tuzel hesap ozelinde vergi mukellefi/fatura kesebilir durumda olmadigim icin gercek ortamda testleri saglayamiyorum. Belirttiginiz ozellik test ortaminda calismadigi icin dogrudan Fatih Kadir Akin (@f) in yazmis oldugu paketeki halini php ye uyarlamistim. Sizlere yardimci olmadigim icin uzgunum.
Kolayliklar dilerim.

**Comment by crazyshark2** [comment]
Çok teşekkür ederim. Şuanki yaptığınızda çok faydalı bir bilgiydi. Keşke paylaşımlar sizlerin Fatih Kadir Akın gibi faydalı bir şekilde yapılsa sadece kendini geliştirmek ve ilerlemek için insanlar çaba sarf etseler. Sürekli aynı kodları çıkarmak için binlerce kişi uğraşmasa zaman kaybetmese başka şeyler çıkarmaya geliştirmeye çalışssa :)

**Comment by ademalidurmus** [comment]
Guzel yorumlariniz icin tesekkurler. Kolayliklar dilerim.
