### ISSUE TITLE
earsiv portal ile ilgili

### ISSUE THREAD

**Issue by serkandiker** [ademalidurmus/fatura#5]
Mükellef bilgileri  güncellemek istediğimde 
Güncelleme işlemi başarısız oldu tekrar deneyiniz. Hata kodu: 2-2305
hata kodu vermekte  anlamını nedir

**Comment by ademalidurmus** [comment]
Merhaba @serkandiker,

`updateUserData` metoduna vermis oldugunuz array icerisinde `buildingName` (apartmanAdi) key ini vermediginiz icin bu hatayi aliyor olabilirsiniz. Degeri bos (empty string) dahi olsa bu parametreyi gondermeniz gerekiyormus. Bu acidan kontrol etmenizi oneririm.

Kolayliklar dilerim.

**Comment by serkandiker** [comment]
Teşekkür ederim bütün dizeleri karakter setine uygun oluşturduğumda Bilgileriniz başarıyla güncellendi. Uyarısını aldım

**Comment by ademalidurmus** [comment]
Rica ederim.
