### ISSUE TITLE
SMS Doğrulaması hakkında

### ISSUE THREAD

**Issue by nrtszr** [AdemAliDurmus/fatura#6]
SMS doğrulaması faturanın oluşturulması için mecburi kullanılması gerekiyor mu?

**Comment by ademalidurmus** [comment]
Merhaba @nrtszr,

Burada (https://github.com/ademalidurmus/fatura/issues/3) belirtmis oldugum uzere fatura olusturmaya dogrudan yetkili olmadigim icin, bu konuda herhangi bilgim yok. Bildigim kadariyla da resmi bir dokuman yok. https://earsivportal.efatura.gov.tr uzerinden yapilan islemler arasinda boyle bir zorunlluk var ise fatura olusturma icin sms dogrulamasi zorunlu diye dusunebilirsiniz. Kutuphanenin PHP versiyonunu hazirlarken [orneklerde](https://github.com/ademalidurmus/fatura/blob/master/example/index.php) boyle bir zorunluluk olmadan fatura olusturabilmistim.

GIB servisinde yapilan guncellemeler kutuphanenin kullanilmasina engeller olusturuyor ise takildiginiz adimlari paylasirsaniz gelistirme yapabilirim.

Kolayliklar dilerim.
