### ISSUE TITLE
jsonencode hakkında

### ISSUE THREAD

**Issue by serkandiker** [AdemAliDurmus/fatura#8]
Adem bey çok teşekkür ediyorum . Chrome DevTools ile canlı sunucu üzerinden  Referans js dosyalarına ulaştım . Verdiğiniz fikir için size minnettarım.İyi çalışmalar diliyorum

**Comment by ademalidurmus** [comment]
Rica ederim @serkandiker Bey. Basarili sonuca varmis olmaniza sevindim.
